### PR TITLE
fix: remove duplicate monitor client classes 

### PR DESCRIPTION
**Pull request by suraj-qlogic**

### CODE REVIEW

**Review by athakor — COMMENTED** [review]
this code is auto generated. so it's better to leave as it is.

**Comment by dmitry-fa** [comment]
@athakor , @suraj-qlogic 
> this code is auto generated. so it's better to leave as it is.

That's true, the code is auto-generated. But looks like they decided to move to another location and just forgot to remove the old copy.

**Review by dmitry-fa — APPROVED** [review]
Looks good.

**Comment by suraj-qlogic** [comment]
@athakor ,I have executed SynthTool in this client and found that's it's generate code inside inner package but does not generate outside package.So just classes are moved inner location.

**Pull request closed without merging**
